= Development
:toc: right
:toclevels: 4
:enonicTasks: https://developer.enonic.com/docs/xp/stable/framework/tasks
:githubWebcrawl: https://github.com/enonic/app-explorer/blob/master/src/main/resources/tasks/webcrawl/webcrawl.ts

== Project structure

In the project folder you will find a file structure similar to this:

.Some selected files from the collector app code:
[source,files]
----
src/
 main/
  resources/
   assets/
     js/
      react/
       Collector.tsx <1>
       useCollectorState.ts <2>
   tasks/
    collect/
     collect.ts
     collect.xml
   collectors.json <3>
   documentTypes.json <4>
gradle.properties <5>
webpack.config.babel.js <6>
----

<1> React component with the form elements.
<2> State code for the React component.
<3> Configuration for one or more collectors present in this application.
<4> Configuration for one or more document-types present in this application.
<5> App settings and name.
<6> Compilation settings.

== build.gradle

This should already be set up in the starter.

.build.gradle
[source,gradle]
----
dependencies {
    include 'com.enonic.lib:lib-explorer:4.0.0'
}
----

== collectors.json

TIP: You can include multiple collectors in a single enonic xp application.

NOTE: If you only include one, the collectors.json file should still contain an array with a single object entry.

CAUTION: Since all collectors are loaded into the same "global" scope in the browser, it's important that each collector has an unique library name. Not only inside a single collector app, but across all installed collector apps.

.src/main/resources/collectors.json
[,json]
----
include::../src/main/resources/collectors.json[]
----

NOTE: The library name must match up between webpack.config.babel.js and src/main/resources/collectors.json

.webpack.config.babel.js
[source,java]
----
const config = {
    entry: {
        'Collector': './Collector.tsx', <1>
    },
    output: {
        filename: '[name].esm.js',
        library: 'Lib[name]', <2>
        libraryTarget: 'var',
    }
}
----
<1> The entry object keys will become part of the library name.
<2> Since the entry name is "Collector", the library name will be "LibCollector".

== documentTypes.json

TIP: You can include multiple document-types in a single enonic xp application.

NOTE: If you only include one, the documentTypes.json file should still contain an array with a single object entry.

CAUTION: Each document-type must have a unique _name property. Not only inside a single collector app, but across all installed collector apps.

[,json]
----
include::../src/main/resources/documentTypes.json[]
----

TIP: The document-type name can then be used when persisting documents in your collector task code:

./src/main/resources/tasks/collect/collect.ts
[source,typescript]
----
collector.persistDocument(documentToPersist, {
    documentTypeName: 'starter_explorer_collector_document_type'
});
----

== React form

In order to understand the example provided in the starter I suggest consulting the <<api/react, Collector React Form>> documentation while reading the code.

=== Collector.tsx

./src/main/resources/assets/js/react/Collector.tsx
[,typescript]
----
include::../src/main/resources/assets/js/react/Collector.tsx[]
----


== Task

An example is provided in the starter.

TIP: A more advanced "example" can be found {githubWebcrawl}[here].

It uses the normal {enonicTasks}[task framework], but has some useful extensions.

=== collect.xml

The task receives the following properties, when called from the Explorer Admin GUI Application:

* collectionId
* collectorId
* configJson
* language

The task descriptor xml must declare these properties:

./src/main/resources/tasks/collect/collect.xml
[,xml]
----
include::../src/main/resources/tasks/collect/collect.xml[]
----

=== collect.ts

The task controller typescript file can then pass on these properties via the Collector class constructor:

./src/main/resources/tasks/collect/collect.ts
[source,typescript]
----
import {Collector} from '/lib/explorer';

export function run({
    collectionId,
    collectorId,
    configJson,
    language
}) {
    const collector = new Collector<CollectorConfig>({
        collectionId, collectorId, configJson, language
    });
}
----

In order to understand the example provided in the starter I suggest consulting the <<api/task, Collector Task API>> documentation while reading the code:

./src/main/resources/tasks/collect/collect.ts
[,typescript]
----
include::../src/main/resources/tasks/collect/collect.ts[]
----