= Build a custom Collector for Explorer
:sectnums:
:toc: right
:toclevels: 6
:enonicStart: https://developer.enonic.com/start
:enonicTasks: https://developer.enonic.com/docs/xp/stable/framework/tasks
:githubWebcrawl: https://github.com/enonic/app-explorer/blob/master/src/main/resources/tasks/webcrawl/webcrawl.ts

This guide takes you through the steps of building a custom Collector for Explorer.

== Introduction

Collectors are implemented as standard XP applications. They essentially consist of two main components:

Form:: A React based user interface that enable search administrators to instruct the collector in it’s specific activities.

Task:: Code that performs the actual retrieval of content for indexing.

This section will guide you through the basic steps of building your own custom collector.

=== Install CLI

The Enonic Command Line Interface is an essential tool for developers working with Enonic.

If you have `npm` on your device, run this command:

  npm install -g @enonic/cli

If not, here are some {enonicStart}[alternative ways to install Enonic CLI^]

To verify that the CLI has been installed, run `enonic -v`. This should output the version of your installed CLI.

To see all available options, simply run `enonic`.

TIP: To upgrade, use `enonic latest`. If there are new versions you will see instructions on how to upgrade.

=== Create a Sandbox

A sandbox is a local developer instance of our platform - Enonic XP. Create a sandbox by running this command in your terminal:

  enonic sandbox create

Give it a name, i.e. `intro`, and select the most recent version of Enonic XP from the list that appears.

=== Start the Sandbox

Start the sandbox with this command:

  enonic sandbox start --dev

Select the `intro` sandbox from the list, and it will boot up in development mode.

TIP: Dev mode will automatically load changes in your code when developing.

=== Create project

To set up a project locally, run the following command and complete the steps:

  enonic project create -r myproject

==== Project structure

The previous step created the folder `myproject`, you should now have an app structure, looking something like this:

.Selected files from the app code:
[source,files]
----
src/
 main/
  resources/
   assets/
     js/
      react/
       Collector.tsx <1>
       useCollectorState.ts <2>
   tasks/
    collect/
     collect.ts
     collect.xml
   collectors.json <3>
   documentTypes.json <4>
gradle.properties <5>
webpack.config.babel.js <6>
----

<1> React component with the form elements
<2> State code for the React component
<3> Configuration for one or more collectors present in this application.
<4> Configuration for one or more document-types present in this application.
<5> App settings and name
<6> Compilation settings

=== Selecting the project sandbox

From the project folder created (i.e. `myproject/`), run this command:

  enonic project sandbox

This command produces a .enonic file, which tells the enonic command which sandbox to use.

=== Building the application

From the project folder created (i.e. `myproject/`), run this command:

  enonic project build

This command produces a .jar file in the folder `build/libs/` i.e. `build/libs/myproject.jar`

=== Deploying the application to the sandbox

From the project folder created (i.e. `myproject/`), run this command:

  enonic project deploy

This command copies the .jar file from the `build/libs/` folder into the sandbox home deploy folder.

== Trying it out

=== Enonic XP Dashboard

Open a web broswer and visit the Enonic XP Dashboard at http://localhost:8080

Either btn:[LOG IN AS ADMIN] or btn:[CREATE AN ADMIN USER] and log in with that.

=== Install Explorer

In order to test the collector you need to install the Explorer application.

Open the Applications app via the topright XP menu, or via http://localhost:8080/admin/tool/com.enonic.xp.app.applications/main

Click the btn:[Install] button.

Find Explorer in the list and click the btn:[Install] button.

=== Open Explorer

Open the Explorer app via the topright XP menu or via http://localhost:8080/admin/tool/com.enonic.app.explorer/explorer

=== Document type

Click the topleft hamburger menu and select btn:[Document types].

Study the `document types`.

Find the one named "starter_explorer_collector_document_type" and click the btn:[Edit] button.

Since this `document type` comes from a collector app, it is markes as managed and shouldn't be edited.

As long as you don't make any changes and click the btn:[Save] button, you can safely click btn:[Yes] to edit the managed `document type`.

When editing the `document type`, you can now see details, edit or delete the `field(s)` contained in the `document type`.

Whenever a new verion of the collector app is deployed, the `document type` will be updated to the new version.

So the best place to change the `document type` is in the collector app itself.

See <<Development>>

=== Collection

==== Create

Click the topleft hamburger menu and select btn:[Collections].

Click the green bottom-right Create collection btn:[+] button.

Fill in a name and select a Default language for the collection. For instance en-US.

Select the `Starter` collector in the collector dropdown.

It will list the managed `document type(s)` the collector contains.

If will also show the React form from the collector app.

Fill in an url in the url input. For instance https://example.com

Finally click the btn:[Save] button.

The collection should now be visible in the list of collections.

==== Collect

In the list of collections, click the btn:[green cloud download] button.

This will start running the task from inside the collector app, using the url you filled in above.

==== Status / Progress

While the collector task is running it's possible to see the status and progress of the task.

Click the topleft hamburger menu and under `Collections` select the btn:[Status] menu item.

On the status page you can keep an eye on the collector while it's running.

==== Journal

When the collector task has finished, you can see the result in the journal.

Click the topleft hamburger menu and under `Collections` select the btn:[Journal] menu item.

If everything went well, you should see a new entry in the journal with 1 success and 0 errors.

=== Documents

Now that you have a collection with a document, you can search for it under the documents page.

To limit the search to only documents from a single collection, open the Collections page and click the btn:[number] in the Documents column. This will open the Documents page with a filter for that collection.

Fill in a search term in the search input. For instance "example" and hit kbd:[Enter].

You should now get a search result with the document and the word you searched for highlighted.

If you search for a word that isn't in the document, the search result should be empty.

=== Interface

==== Create

Now that you have a collection with a document, you can setup an interface to search for it using GraphQL.

Click the topleft hamburger menu and select `Interfaces`.

Click the green bottom-right Create interface btn:[+] button.

Fill in a name for the interface. For instance "my_interface".

Select the collection you created above in the collection dropdown.

Finally click the btn:[Save] button.

==== GraphQL

Now that you have created an interface, you can use it to search for documents using GraphQL.

In the list of interfaces click the btn:[GraphQL icon] button.

This will open a GraphQL editor.

If you aren't familiar with GraphQL, you might want to read up on it https://graphql.org/learn/.

Try to change the searchString to "example" and click the btn:[Play] button.

You should not see a search result with Example highlighted.