= Build a custom Collector for Explorer
:toc: right
:toclevels: 6
:enonicStart: https://developer.enonic.com/start
:enonicTasks: https://developer.enonic.com/docs/xp/stable/framework/tasks
:githubWebcrawl: https://github.com/enonic/app-explorer/blob/master/src/main/resources/tasks/webcrawl/webcrawl.ts

This guide takes you through the steps of building a custom Collector for Explorer.

== Introduction

Collectors are implemented as standard XP applications. They essentially consist of two main components:

Form:: A React based user interface that enable search administrators to instruct the collector in it’s specific activities.

Task:: Code that performs the actual retrieval of content for indexing.

This section will guide you through the basic steps of building your own custom collector.

=== Install CLI

The Enonic Command Line Interface is an essential tool for developers working with Enonic.

If you have `npm` on your device, run this command:

  npm install -g @enonic/cli

If not, here are some {enonicStart}[alternative ways to install Enonic CLI^]

To verify that the CLI has been installed, run `enonic -v`. This should output the version of your installed CLI.

To see all available options, simply run `enonic`.

TIP: To upgrade, use `enonic latest`. If there are new versions you will see instructions on how to upgrade.

=== Create a Sandbox

A sandbox is a local developer instance of our platform - Enonic XP. Create a sandbox by running this command in your terminal:

  enonic sandbox create

Give it a name, i.e. `intro`, and select the most recent version of Enonic XP from the list that appears.

Start the sandbox with this command:

  enonic sandbox start --dev

Select the `intro` sandbox from the list, and it will boot up in development mode.

TIP: Dev mode will automatically load changes in your code when developing.

=== Create project

To set up a project locally, run the following command and complete the steps:

  enonic project create -r myproject

==== Project structure

The previous step created the folder `myproject`, you should now have an app structure, looking something like this:

.Selected files from the app code:
[source,files]
----
src/
 main/
  resources/
   assets/
     js/
      react/
       Collector.tsx <1>
       useCollectorState.ts <2>
   tasks/
    collect/
     collect.ts
     collect.xml
   collectors.json <3>
   documentTypes.json <4>
gradle.properties <5>
webpack.config.babel.js <6>
----

<1> React component with the form elements
<2> State code for the React component
<3> Configuration for one or more collectors present in this application.
<4> Configuration for one or more document-types present in this application.
<5> App settings and name
<6> Compilation settings

=== Selecting the project sandbox

From the project folder created (i.e. `myproject/`), run this command:

  enonic project sandbox

This command produces a .enonic file, which tells the enonic command which sandbox to use.

=== Building the application

From the project folder created (i.e. `myproject/`), run this command:

  enonic project build

This command produces a .jar file in the folder `build/libs/` i.e. `build/libs/myproject.jar`

=== Deploying the application to the sandbox

From the project folder created (i.e. `myproject/`), run this command:

  enonic project deploy

This command copies the .jar file from the `build/libs/` folder into the sandbox home deploy folder.

== Development

=== Including the Explorer Library

This should already be set up in the starter.

.build.gradle
[source,gradle]
----
dependencies {
    include 'com.enonic.lib:lib-explorer:4.0.0'
}
----

=== Configure collectors.json

You can include multiple collectors in a single enonic xp application.
If you only include one, the collectors.json file should still contain an array with a single object entry.

Each collector needs to have it's own unique library name so React can access it on the window object.

The library name must match up between webpack.config.babel.js and src/main/resources/collectors.json

.webpack.config.babel.js
[source,java]
----
const config = {
    entry: {
        'MyCollectorNameA': './CollectorA.jsx',
        'MyCollectorNameB': './CollectorB.jsx',
    },
    output: {
        filename: '[name].esm.js',
        library: 'Lib[name]',
        libraryTarget: 'var',
    }
}
----

./src/main/resources/collectors.json
[source,json]
----
[{
    "componentPath": "window.LibMyCollectorNameA.Collector",
    "configAssetPath": "react/MyCollectorNameA.esm.js",
    "displayName": "My collector A",
    "taskName": "collectA"
},{
    "componentPath": "window.LibMyCollectorNameB.Collector",
    "configAssetPath": "react/MyCollectorNameB.esm.js",
    "displayName": "My collector B",
    "taskName": "collectB"
}]
----

=== Configure documentTypes.json

You can include multiple document-types in a single enonic xp application.
If you only include one, the documentTypes.json file should still contain an array with a single object entry.

Each document-type must have a unique _name property.

Those document-type names can then be used when persisting documents in you collector task code.

./src/main/resources/documentTypes.json
[source,json]
----
[{
    "_name": "starter_explorer_collector_document_type_a",
    "addFields": false,
    "properties": [{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": true,
        "max": 0,
        "min": 0,
        "name": "text",
        "nGram": true,
        "path": false,
        "valueType": "string"
    },{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": true,
        "max": 0,
        "min": 0,
        "name": "title",
        "nGram": true,
        "path": false,
        "valueType": "string"
    },{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": false,
        "max": 0,
        "min": 1,
        "name": "url",
        "nGram": false,
        "path": false,
        "valueType": "string"
    }]
},{
    "_name": "starter_explorer_collector_document_type_b",
    "addFields": false,
    "properties": [{
        "active": true,
        "enabled": true,
        "fulltext": true,
        "includeInAllText": true,
        "max": 0,
        "min": 0,
        "name": "propertyName",
        "nGram": true,
        "path": false,
        "valueType": "string"
    }]
}]
----

./src/main/resources/tasks/collect/collect.ts
[source,typescript]
----
collector.persistDocument(documentToPersist, {
    documentTypeName: 'starter_explorer_collector_document_type_a'
});
----

=== Task(s)

An example is provided in the starter.

TIP: A more advanced "example" can be found {githubWebcrawl}[here].

It uses the normal {enonicTasks}[task framework], but has some useful extensions.

The task receives the following properties, when called from the Explorer Admin GUI Application:

* collectionId
* collectorId
* configJson
* language

The task descriptor xml must declare these properties:

./src/main/resources/tasks/collect/collect.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<task>
	<description>Collect</description>
	<form>
		<input name="collectionId" type="TextLine">
			<label>Collection ID</label>
			<occurrences minimum="0" maximum="1"/>
		</input>
		<input name="collectorId" type="TextLine">
			<label>Collector ID</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
		<input name="configJson" type="TextLine">
			<label>Config JSON</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
		<input name="language" type="TextLine">
			<label>Language</label>
			<occurrences minimum="0" maximum="1"/>
		</input>
	</form>
</task>
----

The task controller typescript file can then pass on these properties via the Collector class constructor:

./src/main/resources/tasks/collect/collect.ts
[source,typescript]
----
import {Collector} from '/lib/explorer';

export function run({
    collectionId,
    collectorId,
    configJson,
    language
}) {
    const collector = new Collector<CollectorConfig>({
        collectionId, collectorId, configJson, language
    });
}
----

==== The Collector Class

The Collector class provides useful methods in order to:

* Provide progress information to the Explorer Admin GUI App.
* Persist documents.
* Provide state information to build an Explorer Journal.
* Make it possible to get whether Explorer Admin wants the collector to stop "midstream" (before it's actually finished).

===== Properties

====== config

Any configuration passed in via configJson is available as a javascript object via the config property.

===== Methods

====== constructor()

This method:

* Throws if any of the parameters are missing or invalid.
* Gets information about the Collection.
* Parses the configJson and provides the result via the config property.

====== start()

This method:

* Stores a startTime timestamp used in duration calculations.
* Reports an initial progress via lib-task.
* Creates a new collection repo (if needed).
* Persists information that the collector is running (so it can't be run twice in parallel, but can be stopped).
* Sets up a journal to write state information to.

====== queryDocuments()

This method makes is possible to query the exisiting documents in the collection.
Useful to find the document id to modify an existing document, rather than creating a new one.

====== persistDocument()

This method will create or modify a document, based on its parameters.
If can also extend a documentType and validate against it.

====== deleteDocument()

This method makes it possible to delete one or more documents from the collection.

====== getDocumentNode()

This method makes it possible to get one ore more documents from the collection.

====== shouldStop()

This method checks whether the STOP button has be clicked in the Explorer Admin GUI.

Useful to finish gracefully, for instance by breaking loops.

====== addSuccess()

Adds a success to the journal.

====== addInformation()

Adds useful information to the journal.

====== addWarning()

Adds a warning to the journal.

====== addError()

Adds an error to the journal.

====== stop()

This method:

* Persists the journal to the journal repo.
* Sends emails if notifications are configured on the Explorer Admin GUI.
* Persists information that the collector has failed or finished (so it can be started again).


=== React form component(s)

In order for your collector's configuration user interface to work in Explorer you must provide a React component.
Any react component type should be supported, but all examples are functional (since that is the current status quo of react).

The component receives four props from Explorer:

. collectorConfig - Config state object.
. setCollectorConfig - A function to modify the config state object.
. setCollectorConfigErrorCount - A function to set how many validation errors the form has.
. ref - A reference which makes it possible for the parent (Explorer Admin) to call functions inside this child component.

==== collectorConfig

This is a standard React.useState object. You can write any nested configuration properties you need to it (using the setCollectorConfig function). When the form is successfully submitted, the state object is persisted. Which means the next time the form is opened, the previous state is available.

==== setCollectorConfig

This is a standard setState function returned by React.useState. Use it to change the state of the collectorConfig object.

==== setCollectorConfigErrorCount

This is a standard setState function returned by React.useState. Use it to allow or prevent form submission. 0 errors are required to allow form submission.

==== ref

The react component can pass two named function references to it's parent component (Explorer Admin).

===== afterReset

In Explorer Admin there is a [Reset] form button. If you need any code to run in your component when this button is clicked pass a function named "afterReset" to the parent via React.useImperativeHandle:

[source,typescript]
----
React.useImperativeHandle(ref, () => ({
    afterReset
}));
----

===== validate

Each time the form state changes, the form is validated. If you need any code to run in your component during validation then pass a function named "validate" to the parent via React.useImperativeHandle:

[source,typescript]
----
React.useImperativeHandle(ref, () => ({
    validate
}));
----
