= Setting up your development environment
:toc: right
:enonicStart: https://developer.enonic.com/start

In this chapter you will create, buid, deploy and run a collector based on a template.

== Introduction

Collectors are implemented as standard Enonic applications. This chapter will guide you through the basic steps of building your own custom collector.

NOTE: The following steps will require https://developer.enonic.com/start[Enonic CLI] to be installed

== Create a sandbox

A sandbox is a local developer instance of our platform - Enonic XP. 

. Create a sandbox called `mycollector` by running this command in your terminal:

  enonic sandbox create mycollector

. Choose the latest version of Enonic XP (default).
. Start the sandbox with this command:

  enonic sandbox start --dev mycollector

TIP: Dev mode is used to automatically load changes in your code when developing.

== Create the app

From a **new terminal window**, run the following command to create the application.

  enonic project create -r starter-collector

IMPORTANT: Choose the sandbox created in the previous step (if you have multiple sandboxes).

[TIP]
====
This command uses the https://github.com/enonic/starter-collector[Collector starter^] Github repo  as a starter (template) for the app.
====

== Build & deploy

From the app folder you created (i.e. `myproject/`), run this command:

  enonic project deploy

The application should now compile, and deploy to the sandbox.

== Give it a spin

. Log into the Enonic Admin
+
Open a web broswer and access the Enonic XP Dashboard at http://localhost:8080, then click btn:[LOG IN AS GUEST], this will sign you in with super user pemissions.
+
. Install Explorer
+
To actually use your new collector you also need to install Explorer itself.
+
Open `XP menu` -> `Applications` and click btn:[Install].
+
Find Explorer in the list and click the btn:[Install] button.
+
With Explorer installed, you can open the Explorer admin from the XP menu: `XP menu` -> `Explorer`
+
. Create collection
+
To try out the new collector, click the hamburger menu and select btn:[Collections].
+
Click the green bottom-right Create collection btn:[+] button. Fill in a name and select a Default language for the collection. For instance en-US.
+
Select the `Sample collector` in the collector dropdown.
+
After selecting the collector, a simple form will appear. This form was bundled with your collector and can be customized to your needs. As you will see laster.
+
Fill in the URL field with this value: `https://example.com`
+
Save the new collection.
+
. Collect
+
Its time to give the collector a spin. From the collections list, simply click the btn:[green cloud download] icon.
+
This will start running the task from inside the collector app, using the url you filled in above. It should complete within seconds, and the document count should increase to `1`.
+
NOTE: If you don't see any changes, try refreshing, check the sandbox logs, or visit the `Journal` menu items - located just below `Collections` in the menu.
+
. Search
+
Now that you have a collection with a document, you may search for it from the btn:[Documents] page.
+
To limit the search to only documents from a single collection, open the Collections page and click the btn:[number] in the Documents column. This will open the Documents page with a filter for that collection.
+
Fill in a search term in the search input. For instance "example" and hit kbd:[Enter].
+
You should now get a search result with the document and the word you searched for highlighted.
+
If you search for a word that isn't in the document, the search result should be empty.


Now that you have your app up and running, it's time to dive into the details.

Continue to <<overview#, the overview chapter>>.
