= Collector task
:toc: right
:toclevels: 4
:enonicTasks: https://developer.enonic.com/docs/xp/stable/framework/tasks

In this chapter you will learn about tasks, the heart of a collector

== Introduction

Collectors essentially build on a standard feature of the Enonic framework - tasks. Tasks provide out-of-the-box support for running background jobs with ease. Also, tasks can be scheduled via the Enonic framework.


== Task 

Tasks are essentially JS controllers, following a specific pattern.

Your app contains an example task, located in the following file structure:

.Application file structure:
[source,files]
----
src/
 main/
  resources/
   tasks/
    sample-collector/ //<1>
     sample-collector.ts //<2>
     sample-collector.xml //<3>
----

<1> The task folder
<2> The task controller: Same name as folder
<3> The task schema. Same name as folder

For more detais on tasks, visit the {enonicTasks}[task documentation].

NOTE: Feel free to give your collector task a different name, but remember to update your `collectors.json` file.

=== Schema

In your application, the schema is called `sample-collector.xml`.

This file will basically look the same for all collector tasks (remember, you may have multiple collectors within a single app). The file basically declares the parameters which will be passed to the controller:

* collectionId
* collectorId
* configJson
* language

./src/main/resources/tasks/collect/collect.xml
[,xml]
----
include::../src/main/resources/tasks/sample-collector/sample-collector.xml[]
----

=== Controller

In your application, the task controller is called `sample-collector.ts`.

NOTE: This task controller is written in TypeScript, and will be compiled to JavaScript when deploying:


*Constructor*

Every collector needs to implement the `run()` function, and accept the standard parameters - as defined above. 

./src/main/resources/tasks/collect/collect.ts
[source,TypeScript]
----
import {Collector} from '/lib/explorer';

export function run({
    collectionId,
    collectorId,
    configJson,
    language
}) {
    const collector = new Collector<CollectorConfig>({
        collectionId, collectorId, configJson, language
    });
}
----

*Persisting*

We will not go into details on the actual implementation of how this collector fetches data, but a common element for probably any collector is to index data in the end.

Remember, a document is essentially a JSON file.

.Example code for persisting a document
[source,TypeScript]
----
collector.persistDocument(documentToPersist, {
        documentTypeName: 'starter_doctype'
    });
    collector.addSuccess({
        message: "Sweet, it worked"
    });
} catch (e) {
    log.error(`message:${e.message}`, e);
    collector.addError({message: `${e.message}`});
}
----

Feel free to study the full task controller code for more details. 

TIP: For a more extensive example - check out the https://github.com/enonic/app-explorer/tree/master/src/main/resources/tasks/webcrawl[Webcrawler collector code]. This Webcrawler is shipped with Explorer by default.

Visit the <<api#, Collector API documentation>> for a complete list of available functions.